ezl/dailyidea.com

back/appsync/mapping-templates/ideas/create-idea/createIdeaItem-request-mapping-template.txt
back/appsync/schema.graphql
back/appsync/serverless.yml
front/components/dialogs/resendAuthEmail.vue
front/graphql/mutations/createIdea.js
front/layouts/default.vue
front/middleware/authenticated.js
front/pages/auth/login/index.vue
front/pages/auth/login/success.vue
front/pages/auth/signup/success.vue
front/pages/auth/verify.vue
front/pages/ideas/create.vue

closes #90
closes #94
closes #95
closes #96
closes #112
closes #112
closes #36
closes #37

Fix of corresponding tickets

---

back/mail-processing/process_incoming_mail.py
back/mail-processing/requirements.txt

Strip out signatures from email idea parser

---

front/components/ideaDetail/IdeaComments.vue
front/components/ideaDetail/IdeaCommentsComment.vue
front/pages/ideas/_userId/_ideaId.vue

Make it possible for comment owner to delete comment

---

front/components/ideaDetail/MenuPanel.vue
front/components/ideaDetail/SaveIdeaBookmark.vue
front/pages/ideas/_userId/_ideaId.vue

@aldarund I made a bunch of changes to ideaDetail page.
Merging it, but doing it through a PR in case you want to review or revert it.

Update idea view page

---

front/components/layout/DesktopHeader.vue
front/components/layout/MobileHeader.vue
front/components/layout/NavigationMenu.vue
front/components/layout/SearchComponent.vue

merging it, but check it out.
basically:
1. moved the search stuff that was duplicated in MobileHeader and DesktopHeader into a single component
2. then "removed" it by making it so it will never render.
I think we'll add search later, and this is where it will be stylistically (basically), so just leaving it until we get to it (soon hopefully)

Refactor search to component

---

front/components/profilePage/UsersProfile.vue
front/conf/.gitignore

fixed default profile pic placement, ignore .env files

---

front/assets/style/common.scss
front/components/layout/DesktopHeader.vue

removed underline for "log in" link in header

---

back/appsync/functions/share_idea/share_idea.html

#329 
Not yet finished, the question about idea content is in ticket

Updated share idea email template

---

back/users/mail-templates/require_login_template.html

Added missing name in title

---

back/appsync/mapping-templates/idea-comments/deleteIdeaTemporaryComment-request-mapping-template.txt
back/appsync/mapping-templates/idea-comments/deleteIdeaTemporaryComment-response-mapping-template.txt
back/appsync/schema.graphql
back/appsync/serverless.yml
front/components/ideaDetail/IdeaComments.vue
front/graphql/mutations/deleteIdeaTemporaryComment.js

don't post comment twice if confirmation link is clicked twice

---

back/mail-processing/README.md
back/mail-processing/mail_templates/request_daily_idea/daily_idea.html
back/mail-processing/mail_templates/request_daily_idea/send_request_daily.py
back/mail-processing/requirements.txt
back/mail-processing/serverless.yml

made links in daily idea reminder authenticate the user

---

back/mail-processing/mail_templates/request_daily_idea/daily_idea.html
front/components/ideasList/ideasList.vue

- Added 1.5 line height to all text
- Made button style the same as the signup email

Issue 348 - Updated Daily Reminder email style

---

back/users/mail-mjml/magic_link_template_with_comment.mjml
back/users/mail-mjml/require_login_template_with_comment.mjml
back/users/mail-templates/magic_link_template_with_comment.html
back/users/mail-templates/require_login_template_with_comment.html
back/users/src/requestLogin.js
front/components/ideaDetail/ActOnIdea.vue

1. Fixed spelling mistake in unauthenticated comments email
2. Unsubscribe and update email preferences direct to settings page
3. Save & Comment completion links fixed to use new idea slug URL

Issue 427 - Unauthenticated Save and Comment fixes

---

front/components/ValidateTextField.vue
front/nuxt.config.js
front/pages/auth/login/index.vue
front/pages/auth/signup/index.vue
front/pages/i/_shortId/_slug.vue
front/pages/ideas/create.vue
front/plugins/directives.js

Added v-focus directive, focus needed fields on render

---

front/components/dialogs/ShareIdeaByEmail.vue

On share, hide logged in user's name if we have it

---

front/components/ideaDetail/IdeaCommentsComment.vue
front/components/ideaDetail/Swiper.vue
front/graphql/query/getSavedIdeas.js

Issue 431 - Fixed idea URL on Saved Ideas page

---

front/components/ideaDetail/Swiper.vue

Implements animation.
- Card continues off screen when swiped
- New card comes in from opposite side of screen 
- Made card more sensitive to swipe

Issue 458 swipe interaction enhancements

---

back/mail-processing/request_daily_idea.py

This one fixes daily emails, it was broken in unsubscribe task

---

README.md

Added Troubleshooting to readme

---

back/users/src/requestLogin.js
front/components/ideaDetail/ActOnIdea.vue
front/components/ideaDetail/AskEmailDialog.vue
front/components/ideaDetail/AskNameDialog.vue
front/components/ideaDetail/LikeIdea.vue
front/components/ideaDetail/SaveIdea.vue
front/pages/auth/verify.vue

This PR fixes two issues where turned out to be very closely related (#456 and #428) and didn't make sense to solve individually. 
1. Unauthenticated like/save would perform both actions regardless of the user's intended action
2. Dialogs did not display properly according to the user's intended action
3. Would break profile page

Issue 456 - Broken account no auth Like/Save

---

front/pages/i/_shortId/_slug.vue

delete idea modal - image is missing

---

front/components/dialogs/RegisterEncourageDialog.vue

fix share success modal style

---

front/components/authPage/LoginCodeInput.vue
front/components/dialogs/ResendAuthEmail.vue
front/nuxt.config.js
front/package.json
front/pages/auth/login/confirm.vue
front/pages/auth/login/index.vue
front/yarn.lock

Login with code flow for mobile

---

back/emails/README.md
back/users/src/requestLogin.js

Added readme how to test emails, fixed signup email

---

back/mail-processing/mail-mjml/weekly_stats/weekly_stats-replace.json
back/mail-processing/mail_templates/weekly_stats/send_weekly_stats.py
back/mail-processing/mail_templates/weekly_stats/weekly_stats.html

Weekly stats: different image based on ideas count

---

front/pages/auth/login/index.vue

fixed email not found error message

---

back/users/package.json
back/users/resources/dynamo-user-table.yml
back/users/serverless.yml
back/users/src/requestLogin.js
back/users/yarn.lock
front/pages/auth/verify.vue

Handle default avatar on backend

---

back/mail-processing/request_daily_idea.py
back/mail-processing/weekly_digest.py
back/mail-processing/weekly_stats.py

Issue 523 - Checking is unsubscribedAt is set properly before sending email

---

front/components/ideasList/ideasListIdea.vue

open idea in new tab

---

front/pages/profile/_userSlug.vue

500 on invalid slug for /profile/<nonexistentusername>

---

back/appsync/mapping-templates/updateEmailNotificationsSettings-request-mapping-template.txt

Fixed unsubscribe setting update

---

front/components/ideaDetail/IdeaCard.vue
front/components/ideaDetail/IdeaCardSkeleton.vue
front/components/ideaDetail/Swiper.vue
front/pages/i/_shortId/_slug.vue

Idea card skeleton

---

front/components/shared/GmailSearchBtn.vue

Added filter for "check gmail" to only search for current day

---

front/pages/settings/index.vue

#486 Fix Typo in text

---

front/components/ideaDetail/Swiper.vue
front/pages/index.vue

Fix Swiping Landing page swipe Functionality

---

front/components/IdeaContent.vue

Fix photos - not clickable and correct sized

---

front/components/welcome/Welcome.vue
front/components/welcome/WelcomePortrait.vue
front/pages/index.vue

Fix Swiping Landing page Design

---

front/components/ideaDetail/Swiper.vue
front/components/layout/Layout.vue

Fixed bug with sticky nav and swiper

---

front/components/ideaDetail/FullIdea.vue
front/components/ideaDetail/LikeIdea.vue
front/components/ideaDetail/SaveIdea.vue
front/components/ideaDetail/ideaSwipeQueue.js
front/components/layout/CategoriesSubHeader.vue
front/components/layout/Links.vue
front/pages/i/_shortId/_slug.vue

Issue 581 - Secondary top nav

---

front/components/profilePage/UserProfileAvatarCropDialog.vue

Increases size of crop circle and lowed quality of image so that it can be sent to AWS without an error.
#583

Issue 583 - Increases size of crop circle

---

front/components/ideaDetail/ideaSwipeQueue.js
front/components/layout/DesktopHeader.vue

Clicking logo now either directs to the explore page or to the home onboarding page.
#589

Issue 589 - Logo 404

---

front/components/IdeaContent.vue

Fixed card images

---

front/components/IdeaContent.vue
front/components/ideaDetail/FullIdea.vue
front/components/ideaDetail/IdeaCard.vue
front/components/ideaDetail/IdeaComments.vue
front/components/ideaDetail/MenuPanel.vue
front/pages/i/_shortId/_slug.vue

[idea focus lightbox] improve click to lightbox (some hacks for now)

---

front/components/IdeaContent.vue
front/components/ideaDetail/FullIdea.vue
front/components/ideaDetail/IdeaCard.vue
front/components/ideaDetail/IdeaCardSkeleton.vue
front/components/ideaDetail/SwipeExplainer.vue
front/components/ideaDetail/ideaSwipeQueue.js
front/pages/i/_shortId/_slug.vue

Fixes #621 and #586 which were caused by the same issue.

Issue 586 - mobile card issues

---

front/components/ideaDetail/IdeaCard.vue
front/components/ideaDetail/IdeaCardSkeleton.vue
front/components/ideaDetail/IdeaComments.vue
front/components/ideaDetail/IdeaShow.vue
front/components/ideaDetail/SwipeExplainer.vue
front/components/ideaDetail/Swiper.vue
front/components/shared/Card.vue
front/pages/i/_shortId/_slug.vue

#638 also addresses the overwritten changes mentioned in #634

Issue 638 card size issues

---

front/components/ideaDetail/MenuPanel.vue

Few visual bugs with idea card menu

---

front/components/ideaDetail/ideaSwipeQueue.js
front/pages/auth/verify.vue

Issue 595 - Redirecting properly to Top Ideas explore page after login/signup

---

front/assets/style/common.scss
front/components/ideaDetail/IdeaCard.vue
front/components/ideaDetail/Swiper.vue
front/components/layout/Layout.vue
front/components/profilePage/UsersProfile.vue
front/components/shared/Card.vue
front/pages/i/_shortId/_slug.vue

[idea focus lightbox] add (X) circle in whitespace to exit lightbox

---

front/components/IdeaContent.vue
front/components/ideaDetail/IdeaShow.vue

Issue 622 bottom of card hidden

---

front/components/ideaDetail/IdeaCard.vue
front/components/ideaDetail/Swiper.vue
front/components/profilePage/UsersProfile.vue

Close button appeared on desktop card, arrows click bug #653

---

front/components/layout/Layout.vue
front/layouts/default.vue

Issue/599 remove facebook chat #599

---

front/components/welcome/WelcomePortrait.vue

[landing page] fix button colors to match design #602

---

front/pages/index.vue

[landing page] don't let instructions disappear at wide viewport #601

---

front/components/welcome/WelcomePortrait.vue

[landing page] set whitespace above button #603

---

front/components/profilePage/UserProfileHeaderSection.vue

[settings] fix padding on header on mobile #611

---

front/pages/index.vue

[landing page] center instructions #604

---

front/pages/index.vue

Issue 658 - Removed min-height requirements and made max-width smaller.

---

front/components/ideaDetail/IdeaCardSkeleton.vue
front/components/shared/Card.vue

Issue 656 - Skeleton card fits behind idea card

---

front/components/IdeaContent.vue
front/components/ideaDetail/IdeaShow.vue
front/pages/profile/_userSlug/index.vue

Issue 657 - 'Read more...' not showing on preview cards and added spacing to cards on profile page

---

back/mail-processing/mail_templates/idea_received_confirmation/send_confirmation_idea_received.py

404 idea created by email link #661

---

front/components/authPage/AuthPage.vue

Remove x-scroll from mobile login page #680

---

front/components/ideaDetail/IdeaContent.vue

bug: only use one column on desktop single idea view #690

Fixed bug: only use one column on desktop single idea view #690

---

front/pages/ideas/create.vue

#507 feat(format bar): hide from post screen mobile only

---

front/components/ideaDetail/SwipeExplainer.vue
front/components/layout/Layout.vue
front/components/layout/Links.vue
front/components/welcome/WelcomeFirst.vue
front/components/welcome/WelcomeSecond.vue
front/components/welcome/WelcomeThird.vue
front/pages/auth/verify.vue
front/pages/ideas-cards.vue
front/pages/index.vue
front/store/ideas.js

Logo link / explore link / redirect after auth: don't load list of last ideas every time #697

---

front/components/ideaDetail/Swiper.vue
front/pages/i/_shortId/_slug.vue

Reverse card animation and "end of stack" plus alert #618

---

front/components/layout/CategoriesSubHeader.vue

bug: move new/top navigation in line with page #707

---

back/mail-processing/serverless.yml

Stop sending "digest" email for now #695

---

front/components/profilePage/UserProfileHeaderSection.vue

bug: number of ideas on profile not matching #705

---

front/pages/auth/login/confirm.vue
front/pages/auth/welcome.vue

After mobile login success, direct to ideas page #677

---

front/components/ideaDetail/IdeaEdit.vue
front/components/profilePage/UserProfileHeaderSection.vue

[follow button] If user is not authenticated, make this direct to a login page #679

---

front/components/profilePage/UserProfileHeaderSection.vue

[settings] add whitespace around follow button #675

---

front/components/layout/CategoriesSubHeader.vue
front/pages/ideas-cards.vue
front/store/ideas.js

switch "new" and "top" in menu #706

---

front/components/welcome/WelcomeContent.vue

bug: Make landing page sequence buttons purple #708

---

front/pages/index.vue

enhancement: Add card reversal pattern to landing page sequence #709

---

front/components/ideaDetail/IdeaContent.vue
front/pages/i/_shortId/_slug.vue

[card order] is sequence preserved on "back" actions? #619

---

front/components/authPage/LinkExpired.vue
front/components/layout/CardLayout.vue
front/pages/auth/unathorized.vue

expired link page fonts are way too big #721

---

front/components/ideaDetail/IdeaContent.vue

bug:make long content cards accessible on desktop #700

---

back/appsync/functions/share_idea/share_idea.py

500 errors on production pages, 404 idea created by email link #661

---

front/components/profilePage/UserProfileHeaderSection.vue

"Others" profile page layout is off #725

---

front/components/ideaDetail/IdeaShow.vue

When creating a new idea, if I leave the text empty, it says "undefined" #728

---

front/components/layout/AppNotifier.vue

New snackbar style #730

---

front/pages/i/_shortId/_slug.vue

The first card on "Explore" is skipped when the user's onboarding #746

---

front/components/shared/Lightbox.vue

Close modals with "Esc" button #748

---

front/components/ideaDetail/IdeaCommentsComment.vue

Temporary comment design #724

---

front/components/ideaDetail/IdeaShow.vue
front/graphql/mutations/saveIdea.js
front/graphql/mutations/unsaveIdea.js
front/pages/i/_shortId/_slug.vue
front/store/ideas.js

"Saving" an Idea won't increase the counter #759

---

back/appsync/schema.graphql
back/appsync/serverless.yml
front/components/ideaDetail/IdeaShow.vue
front/plugins/toRelativeDate.js

Bugs with save / like idea counters

---

front/components/ideaDetail/IdeaContent.vue

Fixed flash of "Read more"

---

front/assets/style/base.scss
front/components/TrixWrapper.vue
front/pages/ideas/create.vue

Idea post page refactor, new design

---

front/components/ideaDetail/IdeaComments.vue

Disable arrow keys navigation when writing a comment #758

---

front/components/dialogs/ShareIdeaByEmail.vue
front/components/ideaDetail/MenuPanel.vue

Sharing idea shares profile link instead of actual idea #763

---

front/components/ideaDetail/Swiper.vue
front/pages/index.vue

Flashing after moving on from 3rd card on Landing page #767

---

back/users/mail-mjml/require_login_template_with_idea_save-replace.json
back/users/mail-templates/require_login_template_with_idea_save.html

Image broken in Login email on production #772

---

back/appsync/mapping-templates/idea-comments/add-comment/createIdeaCommentItem-request-mapping-template.txt

Error message on too long comments #778

---

front/components/ideaDetail/IdeaCommentsComment.vue

Super long words in comments stretch the comment area #779

---

back/appsync/schema.graphql
front/components/404.vue
front/components/ideaDetail/ActOnIdea.vue
front/components/ideaDetail/IdeaComments.vue
front/components/ideasList/ideasListPage.vue
front/pages/ideas-cards.vue

Redirect to "All ideas" doesn't work #784

---

front/components/ideaDetail/MenuPanel.vue

Hide share icon on private ideas #775

---

front/components/ideaDetail/IdeaShow.vue
front/pages/profile/_userSlug/index.vue

The "Make idea private" flow is buggy #793

---

front/components/ideaDetail/Swiper.vue

Fixed left swipe freeze #789

---

front/components/Loading.vue
front/pages/ideas/create.vue

Private idea switch #794

---

front/pages/i/_shortId/_slug.vue
front/pages/ideas/create.vue

Dialog after idea created #358

---

front/components/profilePage/UsersProfile.vue
front/pages/profile/_userSlug/index.vue

paginate / show more ideas on profiles with a lot of ideas #801

---

front/components/Loading.vue
front/pages/index.vue

Text for loading screen #718

---

front/components/home/Pages.vue
front/components/home/SwipeExplainerBar.vue
front/pages/index.vue

Welcome cards fixes #787

---

front/pages/ideas/create.vue

Private tooltip and label edits #813 #814

---

front/pages/ideas/create.vue

Updating layout for Post Formatting Buttons on mobile #805

---

front/components/ideaDetail/FullIdea.vue
front/components/ideaDetail/IdeaShortCard.vue
front/components/ideaDetail/IdeaShow.vue
front/components/ideaDetail/IdeaSwipableCard.vue
front/components/profilePage/UsersProfile.vue
front/pages/i/_shortId/_slug.vue
front/pages/profile/_userSlug/index.vue
front/store/ideas.js

Issue after deleting idea #803

---

front/components/ideaDetail/LikeIdea.vue
front/components/ideaDetail/MenuPanel.vue
front/components/ideaDetail/SaveIdea.vue

Hover state size changing #811

---

front/components/Loading.vue
front/components/profilePage/UsersProfile.vue
front/nuxt.config.js
front/pages/profile/_userSlug/saved.vue
front/pages/profile/_userSlug/settings.vue
front/plugins/global-loading.js
front/store/index.js

My Ideas page transitions #809

---

front/components/shared/Lightbox.vue

Deletion modal opens behind idea modal #824

---

front/components/Loading.vue
front/components/ideaDetail/IdeaShow.vue

A quick flicker of the front page when I go to "My ideas" #823

---

front/components/ideaDetail/IdeaShow.vue
front/pages/profile/_userSlug/index.vue

My profile page on beta gives me a 404 #839

---

front/components/profilePage/UserProfileHeaderSection.vue

Hide Follow & Following Numbers #826

---

front/components/layout/Links.vue

Active/Hover States & Transitions for "Explore" "Post" "My Ideas" #788

---

front/components/layout/DesktopHeader.vue
front/components/layout/Layout.vue
front/components/shared/SwipableCard.vue
front/pages/index.vue

Mobile Card iPhone X #835

---

front/pages/ideas/create.vue

Post Title Crops during post creation on mobile (iPhone X) #836

---

front/components/layout/Links.vue

Make links have the same height #846

---

front/components/layout/CategoriesSubHeader.vue
front/components/layout/Links.vue
front/components/layout/SlidingUnderline.vue
front/components/profilePage/UserProfileHeaderSection.vue

Extend underline sliding behavior for menu options in navigation #847

---

front/components/ideaDetail/IdeaComments.vue
front/components/ideaDetail/IdeaShortCard.vue
front/components/ideaDetail/IdeaShow.vue
front/components/ideaDetail/MenuPanel.vue
front/components/profilePage/UsersProfile.vue

Clicking on the Comment icon should open the idea modal #845

---

front/components/auth/AuthFlow.vue
front/layouts/bare.vue
front/layouts/error.vue
front/pages/ideas/create.vue

Updating the login/signup copy - click the Post tab #863

---

front/components/dialogs/ShareIdeaByEmail.vue
front/components/ideaDetail/FullIdea.vue
front/components/ideaDetail/IdeaLightbox.vue
front/components/ideaDetail/IdeaShortCard.vue
front/components/ideaDetail/IdeaShow.vue
front/components/profilePage/UsersProfile.vue
front/nuxt.config.js
front/package.json
front/pages/profile/_userSlug/saved.vue
front/yarn.lock

Bug with unsaving an idea on profile #867

---

front/components/ideaDetail/MenuPanel.vue

Reduced min width of menu dropdown #870

---

front/components/TrixWrapper.vue
front/components/ideaDetail/IdeaContent.vue

Remove image title/description from idea card #872

---

front/components/dialogs/WelcomeDialog.vue

Fix check gmail button #885

---

front/assets/style/common.scss
front/components/dialogs/ShareIdeaByEmail.vue
front/components/home/Pages.vue
front/components/ideaDetail/IdeaSwipableCard.vue
front/components/ideaDetail/Swiper.vue

UI Update - Welcome Cards #869

---

front/components/layout/Layout.vue
front/components/layout/SlidingUnderline.vue

Added box shadow

---

front/components/ideaDetail/IdeaEdit.vue

turn off card swiping during "edit" mode of an idea #873

---

back/users/mail-mjml/require_login_template_create_idea-replace.json
back/users/mail-mjml/require_login_template_create_idea.mjml
back/users/mail-templates/require_login_template_create_idea.html
back/users/src/requestLogin.js

Create a new email for new post #880

---

front/components/ideaDetail/IdeaCommentsComment.vue

Use word-break: break-word; for comments #779

---

front/components/Loading.vue
front/pages/auth/verify.vue
front/store/index.js

Old Loading Status still being shown after clicking email "Don't worry, it's me" button #807

---

front/components/profilePage/UsersProfile.vue

Change url on idea focus view #930

---

front/components/ideas/IdeaEditor.vue

Fixed import typo (case-sensitivity) #485

---

front/helpers/tiptap/file.js

Cleaned up console.log #485

---

front/components/ideaDetail/IdeaContent.vue
front/components/ideas/IdeaEditor.vue
front/helpers/tiptap/file.js
front/helpers/tiptap/image.js

Editor: use span instead of figure to allow inline placement #935

---

front/components/ideas/IdeaEditor.vue
front/components/ideas/IdeaForm.vue

Custom placeholder for editor #936

---

back/common/utils/idea_utils.py
front/components/ideaDetail/IdeaContent.vue
front/components/ideas/IdeaEditor.vue
front/components/tiptap/ImageView.vue
front/helpers/tiptap/image.js

Image Placement #909

---

front/components/ideaDetail/IdeaContent.vue

Removed forced auto width #909

---

front/helpers/tiptap/image.js

Fixed retrieving width attribute #909

---

front/pages/auth/unathorized-my-ideas.vue

Updated text on my ideas not authorized page #928

---

front/components/auth/AuthFlow.vue

Unintended behavior: Saving an idea as an unauthorized user #950

---

front/assets/images/icons/lamp.svg
front/components/Loading.vue

Added random quotes to loading screen #944

---

front/.eslintrc.js
front/components/dialogs/IdeaCommentsDialog.vue
front/components/ideaDetail/FullIdea.vue
front/components/ideaDetail/IdeaCardSkeleton.vue
front/components/ideaDetail/IdeaComments.vue
front/components/ideaDetail/IdeaContent.vue
front/components/ideaDetail/IdeaLightbox.vue
front/components/ideaDetail/IdeaShortCard.vue
front/components/ideaDetail/IdeaShow.vue
front/components/ideaDetail/IdeaSwipableCard.vue
front/components/ideaDetail/Swiper.vue
front/components/layout/CategoriesSubHeader.vue
front/components/layout/Layout.vue
front/components/layout/SlidingUnderline.vue
front/components/profilePage/UsersProfile.vue
front/components/shared/SwipableCard.vue
front/pages/i/_shortId/_slug.vue
front/pages/index.vue
front/utils/index.js

Issue/949 new idea expand #949

---

front/components/ideaDetail/IdeaComments.vue
front/components/profilePage/UserProfileHeaderSection.vue
front/pages/i/_shortId/_slug.vue

Make "comment attempt by unauth account" flow post comment at end #959

---

front/components/ideaDetail/IdeaContent.vue
front/components/ideas/IdeaEditor.vue
front/helpers/tiptap/file.js
front/helpers/tiptap/image.js

Tiptap image extension: uploading progress bar #933

---

front/components/ideaDetail/IdeaSwipableCard.vue
front/components/shared/SwipableCard.vue
front/pages/i/_shortId/_slug.vue

Animate going away from full screen card #958

---

front/pages/unsubscribe/_userId/_token.vue

Unsubscribe from all page: settings link doesn't work #961

---

front/components/ideaDetail/IdeaShow.vue

Fixed animation #958

---

front/components/ideaDetail/IdeaShow.vue

"Idea views" should be shown only to the poster #976

---

front/components/ideas/IdeaEditor.vue
front/components/ideas/IdeaForm.vue
front/helpers/tiptap/file.js
front/helpers/tiptap/image.js

Deleting attachments from S3 when creating / editing ideas #934

---

front/components/ideas/IdeaEditor.vue

Removed console log #943

---

front/components/ideas/IdeaEditor.vue

hide scroll bar on post new idea #984

---

front/components/auth/AuthFlow.vue
front/components/dialogs/WelcomeDialog.vue
front/pages/ideas/create.vue

Added back btn to "welcome back" dialogue #967

---

front/store/ideas.js

404 when creating a private idea on production #1037
